export * from "./school.dto";
export * from "./school-input.dto";
export * from "./school-update.dto";
export * from "./class.dto";
export * from "./class-input.dto";
export * from "./class-update.dto";
export * from "./student.dto";
export * from "./student-input.dto";
export * from "./student-update.dto";
